### ISSUE TITLE
Internal Size for Backpacks/ Containers is displayed the wrong way around

### ISSUE THREAD

**Issue by PocketQuads** [tarkov-database/frontend#1]
Example: https://tarkov-database.com/item/id=545cdae64bdc2d39198b4568

The Tri Zip has a width of 5 and a height of 6 (both it's own size as well as internal size).
The own size is displayed correctly in the info box on the right, however the internal size is displayed the wrong way around (6x5 when it should be 5x6)

This is the case for all backpacks/ containers.

**Comment by morphy2k** [comment]
Thanks for reporting! It has been fixed.
