### ISSUE TITLE
mod_tactical_000 and mod_mount_000 are both displayed as "Mount 1" on the website

### ISSUE THREAD

**Issue by PocketQuads** [tarkov-database/frontend#2]
Both the `mod_tactical_000` and the `mod_mount_000` mod slots are displayed as "Mount 1" on the website.

Examples:
https://tarkov-database.com/item/id=5ab372a310e891001717f0d8 - Here, Mount 1 represents the `mod_tactical_000` slot ingame
https://tarkov-database.com/item/id=5a329052c4a28200741e22d3 - Here, Mount 1 represents the `mod_mount_000` slot ingame

**Comment by morphy2k** [comment]
Thank you for reporting! It's fixed.
